# Please see the documentation for all configuration options: 
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  msapps-public:
    type: nuget-feed
    url: https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/MSApps/nuget/v3/index.json

updates:
- package-ecosystem: github-actions
  directory: ".github/workflows/"
  groups:
    External-Dependencies:
      applies-to: version-updates
      dependency-type: "production"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "microsoft/AL-Go-Actions/*"
    - dependency-name: "microsoft/AL-Go/*"
  labels:
    - "Automation"
  
- package-ecosystem: nuget
  directory: "/"
  registries:
    - msapps-public
  schedule:
    interval: daily
  open-pull-requests-limit: 20

- package-ecosystem: nuget
  directory: "/build/projects/Apps (W1)"
  registries:
    - msapps-public
  schedule:
    interval: daily
  open-pull-requests-limit: 20