title: "[Idea] "
labels: ["bcidea", "approved"]
body:
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
  - type: input
    id: bcidea
    attributes:
      label: BC Idea Link
      description: Please link to the BC Idea
      placeholder: ex. https://experience.dynamics.com/ideas/idea/?ideaid=123456
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please include the description from the BC Ideas page
      placeholder: Description of BC Idea
    validations:
      required: true