name: Receive PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ 'main', 'releases/*' ]

jobs:
  SavePRNumber:
    runs-on: ubuntu-latest

    steps:        
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: pr
          path: pr/