name: Receive PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ 'main', 'releases/*' ]

jobs:
  SavePRNumber:
    runs-on: ubuntu-latest

    steps:        
      - name: Save PR number
        run: |
          echo ${{ github.event.number }}