name: Receive PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ 'main', 'releases/*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/