name: Submit Stability Job On Official Branches

on:
  workflow_dispatch:

permissions: read-all

jobs:
  GetBranches:
    name: Get Official Branches
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.sha }}
      - name: Run Powershell script
        shell: pwsh
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          . (Join-Path "." "build/scripts/tests/runTests.ps1")