name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is {TEMPLATEURL})
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  UpdateALGoSystemFiles:
    name: 'Update AL-Go System Files'
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: aholstrup1/AL-Go/Actions/DumpWorkflowInfo@inputs_settings
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Initialize the workflow
        id: init
        uses: aholstrup1/AL-Go/Actions/WorkflowInitialize@inputs_settings
        with:
          shell: powershell

      - name: Read settings
        uses: aholstrup1/AL-Go/Actions/ReadSettings@inputs_settings
        with:
          shell: powershell
          get: templateUrl

      - name: Read secrets
        id: ReadSecrets
        uses: aholstrup1/AL-Go/Actions/ReadSecrets@inputs_settings
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Update AL-Go system files
        uses: aholstrup1/AL-Go/Actions/CheckForUpdates@inputs_settings
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ env.downloadLatest }} ${{ fromJson(env.settings).inputs.downloadLatest || 'true' }}
          update: 'Y'
          templateUrl: ${{ fromJson(env.settings).inputs.templateUrl || fromJson(env.settings).templateUrl }}
          directCommit: ${{ fromJson(env.settings).inputs.directCommit || fromJson(env.settings).commitOptions.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: aholstrup1/AL-Go/Actions/WorkflowPostProcess@inputs_settings
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
