name: Work Item Validation
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write

defaults:
  run:
    shell: pwsh

jobs:
  WorkItemValidation:
    name: 'Validate link to issues'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Link work items to pull request if possible
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          build/scripts/PullRequestValidation/LinkPullRequestToWorkItem.ps1 -PullRequestNumber ${{ github.event.pull_request.number }} -Repository ${{ github.repository }}

      - name: Validate work items for pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          build/scripts/PullRequestValidation/ValidateIssuesForPullRequest.ps1 -PullRequestNumber ${{ github.event.pull_request.number }} -Repository ${{ github.repository }}
  
  WorkitemValidationForMicrosoft:
    name: 'For Microsoft: Validate link to internal workitems' 
    runs-on: ubuntu-latest
    needs: WorkItemValidation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate internal work items for pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          build/scripts/PullRequestValidation/ValidateInternalWorkitemForPullRequest.ps1 -PullRequestNumber ${{ github.event.pull_request.number }} -Repository ${{ github.repository }}


  AddMilestoneToPullRequest:
    name: 'Add milestone to PR'
    runs-on: ubuntu-latest
    needs: WorkitemValidationForMicrosoft
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add milestone to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          build/scripts/PullRequestValidation/AddMilestoneToPullRequest.ps1 -PullRequestNumber ${{ github.event.pull_request.number }} -Repository ${{ github.repository }}