name: Work Item Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ 'main', 'releases/*' ]

permissions: read-all

defaults:
  run:
    shell: pwsh

jobs:
    WorkItemValidationForMicrosoft:
        name: 'For Microsoft: Validate link to internal work items'
        runs-on: ubuntu-latest
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
            with:
              egress-policy: audit
            
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            
          - name: Validate work items for pull request
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              build/scripts/PullRequestValidation/ValidateIssuesForPullRequest.ps1 -PullRequestNumber ${{ github.event.pull_request.number }} -Repository ${{ github.repository }} -ValidateOnly

          - name: Validate internal work items for pull request
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              build/scripts/PullRequestValidation/ValidateInternalWorkItemForPullRequest.ps1 -PullRequestNumber ${{ github.event.pull_request.number }} -Repository ${{ github.repository }} -ValidateOnly